name: JaCoCoWorkFlow
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build and Analyze with JaCoCo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        run: mvn clean verify -P jacoco-coverage

      - name: Save JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: JaCoCoReport
          path: jacoco-coverage/target/site/jacoco-aggregate/
