name: TestWorkFlow
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8.0.372
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean verify
      - name: Upload Failsafe report
        uses: actions/upload-artifact@v3
        with:
          name: FailsafeReport
          path: bookkeeper-server/target/failsafe-reports
          if-no-files-found: error
      - name: Upload Surefire report
        uses: actions/upload-artifact@v3
        with:
          name: SurefireReport
          path: bookkeeper-server/target/surefire-reports
          if-no-files-found: error
