name: TestWorkFlow
on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Pulisci cache Maven
        run: rm -rf ~/.m2/repository/org/apache/bookkeeper

      - name: Usa settings.xml personalizzato
        run: |
          mkdir -p ~/.m2
          echo "<settings><mirrors><mirror><id>apache-snapshots</id><url>https://repository.apache.org/snapshots</url><mirrorOf>apache.snapshots</mirrorOf></mirror></mirrors></settings>" > ~/.m2/settings.xml

      - name: Run Tests
        run: mvn clean test -U -e


